#!/bin/bash
# Script to run democratic_engine.py for all policy domains and save outputs to markdown files

# Create output directory if it doesn't exist
mkdir -p output

# Define policy domains to process
domains=(
    "economy"
    "healthcare" 
    "education"
    "immigration"
    "climate"
    "infrastructure"
)

echo "🚀 Starting Democratic Machine Learning System - LLM Enhanced Governance Modeling"
echo "📋 Processing $((${#domains[@]})) policy domains..."
echo ""

# Process each domain
for domain in "${domains[@]}"; do
    echo "📊 Processing domain: $domain"
    
    # Run the democratic engine for this domain
    output=$(python3 democratic_engine.py --domain "$domain" --citizens default 2>&1)
    
    # Create intuitive filename
    filename="output/us_${domain}_governance_model.md"
    
    # Save output to markdown file with proper formatting
    {
        echo "# United States $domain Governance Model"
        echo ""
        echo "*Generated by Democratic Machine Learning System with LLM Enhancement*"
        echo ""
        echo "---"
        echo ""
        echo "$output"
        echo ""
        echo "---"
        echo ""
        echo "*Model completed at: $(date)*"
        echo "*LLM Endpoint: http://localhost:8080*"
    } > "$filename"
    
    echo "   ✅ Saved to: $filename"
    echo ""
done

echo "🎉 All domains processed successfully!"
echo "📁 Output files saved in: ./output/"
echo ""
echo "📋 Generated files:"
ls -la output/
echo ""
echo "💡 Each markdown file contains:"
echo "   • Complete governance model output"
echo "   • LLM-enhanced policy analysis (when available)"
echo "   • Trust-weighted voting results"
echo "   • Fairness constraint assessments"
echo "   • Anti-pattern detection results"
echo ""
echo "🔧 To view any file: cat output/us_<domain>_governance_model.md"
